# Generated by Django 2.0.5 on 2018-05-29 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beatcount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track1', models.CharField(max_length=20)),
                ('track2', models.CharField(max_length=20)),
                ('track3', models.CharField(max_length=20)),
                ('track4', models.CharField(max_length=20)),
                ('track5', models.CharField(max_length=20)),
                ('track6', models.CharField(max_length=20)),
                ('track7', models.CharField(max_length=20)),
                ('track8', models.CharField(max_length=20)),
                ('track9', models.CharField(max_length=20)),
                ('track10', models.CharField(max_length=20)),
                ('track11', models.CharField(max_length=20)),
                ('track12', models.CharField(max_length=20)),
                ('track13', models.CharField(max_length=20)),
                ('track14', models.CharField(max_length=20)),
                ('track15', models.CharField(max_length=20)),
                ('track16', models.CharField(max_length=20)),
                ('track17', models.CharField(max_length=20)),
                ('track18', models.CharField(max_length=20)),
                ('track19', models.CharField(max_length=20)),
                ('track20', models.CharField(max_length=20)),
                ('track21', models.CharField(max_length=20)),
                ('track22', models.CharField(max_length=20)),
                ('track23', models.CharField(max_length=20)),
                ('track24', models.CharField(max_length=20)),
                ('track25', models.CharField(max_length=20)),
                ('track26', models.CharField(max_length=20)),
                ('track27', models.CharField(max_length=20)),
                ('track28', models.CharField(max_length=20)),
                ('track29', models.CharField(max_length=20)),
                ('track30', models.CharField(max_length=20)),
                ('track31', models.CharField(max_length=20)),
                ('track32', models.CharField(max_length=20)),
                ('track33', models.CharField(max_length=20)),
                ('track34', models.CharField(max_length=20)),
                ('track35', models.CharField(max_length=20)),
                ('track36', models.CharField(max_length=20)),
                ('track37', models.CharField(max_length=20)),
                ('track38', models.CharField(max_length=20)),
                ('track39', models.CharField(max_length=20)),
                ('track40', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
