# Generated by Django 2.1.5 on 2019-06-24 22:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beatcount', '0007_auto_20180707_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('track1', models.IntegerField()),
                ('track2', models.IntegerField()),
                ('track3', models.IntegerField()),
                ('track4', models.IntegerField()),
                ('track5', models.IntegerField()),
                ('correct', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
