# Generated by Django 2.1.5 on 2019-06-24 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beatcount', '0008_answer2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer2',
            new_name='rAnswer',
        ),
    ]
