# Generated by Django 2.1.5 on 2019-11-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatcount', '0011_test1'),
    ]

    operations = [
        migrations.AddField(
            model_name='test1',
            name='name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
