# Generated by Django 2.1.5 on 2019-11-17 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beatcount', '0014_t1'),
    ]

    operations = [
        migrations.CreateModel(
            name='T2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('track1', models.IntegerField()),
                ('track2', models.IntegerField()),
                ('track3', models.IntegerField()),
                ('track4', models.IntegerField()),
                ('track5', models.IntegerField()),
                ('correct', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
