# Generated by Django 2.1.5 on 2019-11-18 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beatcount', '0016_t3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test1',
            old_name='track1',
            new_name='track21',
        ),
        migrations.RenameField(
            model_name='test1',
            old_name='track11',
            new_name='track24',
        ),
        migrations.RenameField(
            model_name='test1',
            old_name='track12',
            new_name='track26',
        ),
        migrations.RenameField(
            model_name='test1',
            old_name='track14',
            new_name='track27',
        ),
        migrations.RenameField(
            model_name='test1',
            old_name='track16',
            new_name='track28',
        ),
        migrations.RenameField(
            model_name='test1',
            old_name='track17',
            new_name='track29',
        ),
        migrations.RenameField(
            model_name='test1',
            old_name='track18',
            new_name='track30',
        ),
        migrations.RenameField(
            model_name='test1',
            old_name='track2',
            new_name='track32',
        ),
        migrations.RenameField(
            model_name='test1',
            old_name='track6',
            new_name='track36',
        ),
        migrations.RenameField(
            model_name='test1',
            old_name='track8',
            new_name='track37',
        ),
        migrations.RenameField(
            model_name='test1',
            old_name='track9',
            new_name='track38',
        ),
        migrations.RenameField(
            model_name='test2',
            old_name='track10',
            new_name='track22',
        ),
        migrations.RenameField(
            model_name='test2',
            old_name='track13',
            new_name='track23',
        ),
        migrations.RenameField(
            model_name='test2',
            old_name='track15',
            new_name='track25',
        ),
        migrations.RenameField(
            model_name='test2',
            old_name='track19',
            new_name='track31',
        ),
        migrations.RenameField(
            model_name='test2',
            old_name='track20',
            new_name='track33',
        ),
        migrations.RenameField(
            model_name='test2',
            old_name='track3',
            new_name='track34',
        ),
        migrations.RenameField(
            model_name='test2',
            old_name='track4',
            new_name='track35',
        ),
        migrations.RenameField(
            model_name='test2',
            old_name='track5',
            new_name='track39',
        ),
        migrations.RenameField(
            model_name='test2',
            old_name='track7',
            new_name='track40',
        ),
    ]
